# Generated by Django 3.0.7 on 2020-11-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('cellphone', models.CharField(max_length=50)),
                ('fb_link', models.CharField(max_length=50)),
                ('reviews', models.CharField(max_length=50)),
            ],
        ),
    ]
