# Generated by Django 3.1.3 on 2020-11-06 00:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('refence', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=20)),
                ('birth', models.DateField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('calories', models.FloatField()),
                ('goal', models.CharField(max_length=30)),
                ('health_condition', models.CharField(max_length=30)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('period', models.CharField(max_length=20)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
