# Generated by Django 3.1.3 on 2020-11-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='calories',
            field=models.IntegerField(),
        ),
    ]
