# Generated by Django 3.1.3 on 2020-12-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201123_2215'),
        ('clients', '0005_client_week_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='health_condition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='week_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.weekmenu'),
        ),
    ]
